export default [
  {
    _id: "123",
    username: "iron_man",
    password: "stark123",
    firstName: "Tony",
    lastName: "Stark",
    email: "tony@stark.com",
    dob: "1970-05-29T00:00:00.000Z",
    role: "FACULTY",
  },
  {
    _id: "234",
    username: "dark_knight",
    password: "wayne123",
    firstName: "Bruce",
    lastName: "Wayne",
    email: "bruce@wayne.com",
    dob: "1972-02-19",
    role: "STUDENT",
  },
  {
    _id: "345",
    username: "black_widow",
    password: "romanoff123",
    firstName: "Natasha",
    lastName: "Romanoff",
    email: "natasha@avengers.com",
    dob: "1984-11-22",
    role: "TA",
  },
];
